# Generated by Django 5.2.5 on 2025-08-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ad",
            new_name="ads_ad_status_eb9ea6_idx",
            old_name="ads_ad_status_idx",
        ),
        migrations.RenameIndex(
            model_name="ad",
            new_name="ads_ad_propert_f0d42d_idx",
            old_name="ads_ad_property_type_idx",
        ),
        migrations.RenameIndex(
            model_name="ad",
            new_name="ads_ad_monthly_976098_idx",
            old_name="ads_ad_monthly_rent_idx",
        ),
        migrations.RenameIndex(
            model_name="ad",
            new_name="ads_ad_created_9f5b83_idx",
            old_name="ads_ad_created_at_idx",
        ),
    ]
